# Generated by Django 5.0.6 on 2024-06-01 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_product_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="product",
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
