# Generated by Django 5.0.6 on 2024-06-01 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0004_remove_product_product"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="user",
        ),
    ]
