# Generated by Django 5.0.6 on 2024-06-01 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0006_product_products_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.FloatField(null=True),
        ),
    ]
