# Generated by Django 5.0.6 on 2024-06-01 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0008_remove_product_products_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="products_id",
            field=models.IntegerField(default=0),
        ),
    ]
