# Generated by Django 5.0.6 on 2024-06-04 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0010_remove_product_products_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
