name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }}"
      - run: echo "Job is now running on a ${{ runner.os }}"
      - run: echo "Branch name is ${{ github.ref }}"
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "The ${{ github.repository }}} has ben cloned"
      - run: echo "The workflow is now ready"
        name: List files in the repository
      - run: |
          ls ${{ github.workspace }}
      - run: echo "This job's status is ${{ job.status }}"
